### ISSUE TITLE
UI Device Mock

### ISSUE THREAD

**Issue by JoshuaBuditama** [JoshuaBuditama/slowvid#45]
As the client,
so that I know how the final product would look like as a mobile application,
I want the prototype to reflect the mobile application UI.

**Comment by JakeBrown** [comment]
<img width="1435" alt="Screen Shot 2020-10-09 at 10 34 09 am" src="https://user-images.githubusercontent.com/2832256/95525232-1ce38680-0a1b-11eb-8d19-61014940cafb.png">

Here's what I have implemented. Pushing a branch and filing a PR now.

**Comment by JakeBrown** [comment]
Completed
