### ISSUE TITLE
Upload Page

### ISSUE THREAD

**Issue by cskeogh** [JoshuaBuditama/slowvid#47]
As a user,
I want an upload page,
so I can upload my data to a health care professionals.

Design notes, see 'Upload Page' [User Interface Sketches](https://github.com/JoshuaBuditama/slowvid/tree/master/doc/design#user-interface-sketches)

**Comment by JoshuaBuditama** [comment]
Is this the same as Issue #31 ?
If so, it has been addressed in PR #71 

If not, then it's all good 👍

**Comment by cskeogh** [comment]
Duplicate of #31
