### ISSUE TITLE
Upload Complete Page

### ISSUE THREAD

**Issue by cskeogh** [JoshuaBuditama/slowvid#49]
As a user,
I want an upload complete page,
so I know my data has been successfully uploaded to a health care professionals.

Design notes, see '4. Upload Complete Page' [User Interface Sketches](https://github.com/JoshuaBuditama/slowvid/tree/master/doc/design#user-interface-sketches)

**Comment by JoshuaBuditama** [comment]
Has been addressed in PR #83 .
Closing this issue.
