### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by JakeBrown** [JoshuaBuditama/slowvid#6]
Do we want to use Github actions to automatically build and run unit tests? We could potentially set this up to run vulnerability scanning on our dependencies on every deploy. I'll set up a PR which someone can approve if we want to add this.

**Comment by JoshuaBuditama** [comment]
@JakeBrown 
I think that would be great to have since it would ensure that every deployed version of the app will be secure but will it be hard to setup?

**Comment by JakeBrown** [comment]
The Github actions server is already set up as of this PR: https://github.com/JoshuaBuditama/slowvid/pull/7

- To get it to run unit testing and even deploy on commit is pretty trivial. 
- To get it to run vulnerability scanning, no idea! We can keep this issue as a maybe. It lives separate from the other code so we could merge it at any time without merge conflicts.

**Comment by JakeBrown** [comment]
Deleted back-end tests (back-end not set up yet) and merged PR.
